language: node_js
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
node_js:
  - 10
install:
  - npm ci
script:
  - npm test
  - echo "$TRAVIS_EVENT_TYPE"
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"
  - echo "TRAVIS_BUILD_STAGE_NAME"
before_deploy:
  - npm run product
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true

#  on:
#    tags: true
#    branch: master

#stages:
#  - name: before_deploy
#    if: branch = master AND tag IS present
#  - name: deploy
#    if: branch = master AND tag IS present

