language: node_js
node_js:
  - 10
#branches:
#  only:
#    - master
install:
  - npm ci
script:
  - npm test
before_deploy:
  - npm run product
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
