version: 2.1
executors:
  init:
    docker:
      - image: "circleci/node:10.16.3"
jobs:
  build-and-test:
    executor: init
    steps:
      - checkout
      - run: npm ci
      - run: npm test
    branches:
      only:
        - master
        - /v[0-9]+(\.[0-9]+).*/

workflows:
    build-and-test:
      jobs:
        - build-and-test
