version: 2.1
executors:
  init:
    docker:
      - image: "circleci/node:10.16.3"
jobs:
  build-and-test:
    executor: init
    steps:
      - checkout
      - run:
          name: "Run install"
          command: npm ci
      - run:
          name: "Run test"
          command: npm test
workflows:
    build-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only:
                  - master
                  - /v[0-9]+(\.[0-9]+).*/
