version: 2.1
executors:
  init:
    docker:
      - image: "circleci/node:10.16.3"
jobs:
  build-and-test:
    executor: init
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  deploy:
    executor: init
    steps:
      - checkout
      - run: npm run product
workflows:
    build-test-and-deploy:
      jobs:
        - build-and-test:
            filters:
              branches:
                only:
                  - master
                  - /v[0-9]+(\.[0-9]+).*/
        - deploy:
            requires:
              - build-and-test
            filters:
              tags:
                only:
                  - /v[0-9]+(\.[0-9]+).*/
